experiment:
  dataset: exp_no_tempo_final
  data_config:
    strategy: dataset
    dataset_path: lfm_child_10.tsv
    side_information:
    - dataloader: ItemAttributes
      attribute_file: song_features_no_tempo.tsv
  prefiltering:
    - strategy: iterative_k_core
      core: 10
  binarize: True
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.999
      folds: 5
  gpu: 0
  models:
    FM:
      meta:
        save_recs: True
      epochs: 10
      batch_size: 512
      factors: 10
      lr: 0.001
      reg: 0.1
  evaluation:
    simple_metrics: [nDCG, MRR]
  top_k: 10